src/Models/Album.cs
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace PhotoGallery.Models
{
    public class Album : IPaginator
    {
        private AlbumCollection _ac;

        public Album(string absolutePath, AlbumCollection ac)
        {
            _ac = ac;
            AbsolutePath = absolutePath;
            Name = new DirectoryInfo(AbsolutePath).Name;
            Photos = new List<Photo>();
        }

        public string Name { get; }

        public string UrlName
        {
            get
            {
                return Name.Replace(" ", "%20").ToLowerInvariant();
            }
        }

        public string Link
        {
            get
            {
                return $"/album/{UrlName}/";
            }
        }

        public string AbsolutePath { get; }

        public List<Photo> Photos { get; private set; }

        public Photo CoverPhoto
        {
            get
            {
                return Photos?.FirstOrDefault();
            }
        }

        public IPaginator Next
        {
            get
            {
                int index = _ac.Albums.IndexOf(this);

                if (index < _ac.Albums.Count - 1)
                {
                    return _ac.Albums[index + 1];
                }

                return null;
            }
        }

        public IPaginator Previous
        {
            get
            {
                int index = _ac.Albums.IndexOf(this);

                if (index > 0)
                {
                    return _ac.Albums[index - 1];
                }

                return null;
            }
        }

        /// <summary>
        /// Sorts the photos in the album.
        /// </summary>
        public void Sort()
        {
            Photos = Photos.OrderBy(p => p.DisplayName).ToList();
        }

    }
}

src/Pages/Album.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PhotoGallery.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;

namespace PhotoGallery.Pages
{
    public class AlbumsModel : PageModel
    {
        private AlbumCollection _ac;
        private IHostingEnvironment _environment;
        private ImageProcessor _processor;

        public AlbumsModel(AlbumCollection ac, IHostingEnvironment environment, ImageProcessor processor)
        {
            _ac = ac;
            _environment = environment;
            _processor = processor;
        }

        public Album Album { get; private set; }

        public IActionResult OnGet(string name)
        {
            Album = _ac.Albums.FirstOrDefault(a => a.Name.Equals(name, StringComparison.OrdinalIgnoreCase));

            if (Album == null)
            {
                return NotFound();
            }

            return Page();
        }

        [Authorize]
        [ValidateAntiForgeryToken]
        public IActionResult OnPostDelete(string name)
        {
            string path = Path.Combine(_environment.WebRootPath, "albums", name);

            if (Directory.Exists(path))
                Directory.Delete(path, true);

            var album = _ac.Albums.FirstOrDefault(a => a.Name.Equals(name, StringComparison.OrdinalIgnoreCase));

            if (album != null)
            {
                _ac.Albums.Remove(album);
            }

            return new RedirectResult("~/");
        }

        [Authorize]
        public IActionResult OnPostCreate(string name)
        {
            string path = Path.Combine(_environment.WebRootPath, "albums", name);

            Directory.CreateDirectory(path);
            var album = new Album(path, _ac);
            _ac.Albums.Insert(0, album);
            _ac.Sort();

            return new RedirectResult($"~/album/{WebUtility.UrlEncode(name).Replace('+', ' ')}/");
        }

        [Authorize]
        public async Task<IActionResult> OnPostUpload(string name, ICollection<IFormFile> files)
        {
            var album = _ac.Albums.FirstOrDefault(a => a.Name.Equals(name, StringComparison.OrdinalIgnoreCase));

            foreach (var file in files.Where(f => _ac.IsImageFile(f.FileName)))
            {
                string fileName = Path.GetFileName(file.FileName);
                string filePath = Path.Combine(_environment.WebRootPath, "albums", album.Name, Path.GetFileName(fileName));

                if (System.IO.File.Exists(filePath))
                {
                    filePath = Path.ChangeExtension(filePath, file.GetHashCode() + Path.GetExtension(filePath));
                }

                using (var imageStream = file.OpenReadStream())
                using (var fileStream = new FileStream(filePath, FileMode.Create, FileAccess.Write))
                {
                    _processor.CreateThumbnails(imageStream, filePath);
                    await file.CopyToAsync(fileStream);
                }

                var photo = new Photo(album, new FileInfo(filePath));
                album.Photos.Insert(0, photo);
            }

            album.Sort();

            return new RedirectResult($"~/album/{WebUtility.UrlEncode(name).Replace('+', ' ')}/");
        }
    }
}

src/Pages/Albums.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PhotoGallery.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace PhotoGallery.Pages
{
    public class AlbumsModel : PageModel
    {
        private AlbumCollection _ac;
        private IHostingEnvironment _environment;
        private ImageProcessor _processor;

        public AlbumsModel(AlbumCollection ac, IHostingEnvironment environment, ImageProcessor processor)
        {
            _ac = ac;
            _environment = environment;
            _processor = processor;
        }

        public Album Album { get; private set; }

        public void OnGet(string name)
        {
            Album = _ac.Albums.FirstOrDefault(a => a.Name.Equals(name, StringComparison.OrdinalIgnoreCase));
            ViewData["Title"] = Album.Name;
        }

        [Authorize]
        [ValidateAntiForgeryToken]
        public IActionResult OnPostDelete(string name)
        {
            string path = Path.Combine(_environment.WebRootPath, "albums", name);

            if (Directory.Exists(path))
                Directory.Delete(path, true);

            var album = _ac.Albums.FirstOrDefault(a => a.Name.Equals(name, StringComparison.OrdinalIgnoreCase));

            if (album != null)
            {
                _ac.Albums.Remove(album);
            }

            return new RedirectResult("~/");
        }

        [Authorize]
        public IActionResult OnPostCreate(string name)
        {
            string path = Path.Combine(_environment.WebRootPath, "albums", name);

            Directory.CreateDirectory(path);
            var album = new Album(path);
            _ac.Albums.Insert(0, album);

            return new RedirectResult($"~/albums/{name}/");
        }

        [Authorize]
        public async Task<IActionResult> OnPostUpload(string name, ICollection<IFormFile> files)
        {
            foreach (var file in files.Where(f => _ac.IsImageFile(f.FileName)))
            {
                var album = _ac.Albums.FirstOrDefault(a => a.UrlName.Equals(name, StringComparison.OrdinalIgnoreCase));
                string path = Path.Combine(_environment.WebRootPath, "albums", album.Name, Path.GetFileName(file.FileName));

                if (System.IO.File.Exists(path))
                {
                    path = Path.ChangeExtension(path, file.GetHashCode() + Path.GetExtension(path));
                }

                using (var stream = new FileStream(path, FileMode.Create, FileAccess.Write))
                {
                    await file.CopyToAsync(stream);
                }

                _processor.CreateThumbnails(name, path);

                var photo = new Photo(album, new FileInfo(path));
                album.Photos.Insert(0, photo);
            }

            return new RedirectResult($"~/albums/{name}/");
        }
    }
}

src/Pages/Login.cshtml.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Cryptography.KeyDerivation;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using System;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;

namespace PhotoGallery.Pages
{
    public class LoginModel : PageModel
    {
        private IConfiguration _config;

        public LoginModel(IConfiguration config)
        {
            _config = config;
        }

        public async Task OnGet()
        {
            if (HttpContext.Request.Query.Any(q => q.Key == "logout") && User.Identity.IsAuthenticated)
            {
                await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

                RedirectFromLogin();
            }
        }

        public async Task OnPost(string username, string password, string remember)
        {
            if (username == _config["user:username"] && VerifyHashedPassword(password))
            {
                var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
                identity.AddClaim(new Claim(ClaimTypes.Name, _config["user:username"]));

                var principle = new ClaimsPrincipal(identity);
                var properties = new AuthenticationProperties { IsPersistent = remember == "on" };
                await HttpContext.SignInAsync(principle, properties);

                RedirectFromLogin();
            }
        }

        private void RedirectFromLogin()
        {
            if (Request.HasFormContentType &&
                Request.Form.TryGetValue("referrer", out var referrer) &&
                Uri.TryCreate(referrer.ToString(), UriKind.Absolute, out Uri url) &&
                url.Authority == Request.Host.Value)
            {
                HttpContext.Response.Redirect(url.ToString());
            }
            else if (HttpContext.Request.Query.TryGetValue("returnUrl", out var returnUrl))
            {
                HttpContext.Response.Redirect(returnUrl.ToString());
            }
            else
            {
                HttpContext.Response.Redirect("/");
            }
        }

        private bool VerifyHashedPassword(string password)
        {
            byte[] saltBytes = Encoding.UTF8.GetBytes(_config["user:salt"]);

            byte[] hashBytes = KeyDerivation.Pbkdf2(
                password: password,
                salt: saltBytes,
                prf: KeyDerivationPrf.HMACSHA1,
                iterationCount: 1000,
                numBytesRequested: 256 / 8
            );

            string hashText = BitConverter.ToString(hashBytes).Replace("-", string.Empty);
            return hashText == _config["user:password"];
        }
    }
}

src/Pages/Photo.cshtml.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PhotoGallery.Models;
using System;
using System.IO;
using System.Linq;
using System.Net;

namespace PhotoGallery.Pages
{
    public class PhotoModel : PageModel
    {
        private AlbumCollection _ac;
        private IHostingEnvironment _environment;

        public PhotoModel(AlbumCollection ac, IHostingEnvironment environment)
        {
            _ac = ac;
            _environment = environment;
        }

        public Photo Photo { get; set; }

        public void OnGet(string albumName, string photoName)
        {
            var album = _ac.Albums.FirstOrDefault(a => a.Name.Equals(albumName, StringComparison.OrdinalIgnoreCase));
            Photo = album.Photos.FirstOrDefault(p => p.DisplayName.Equals(photoName, StringComparison.OrdinalIgnoreCase));
        }

        public IActionResult OnPostRename(string albumName, string photoName)
        {
            var album = _ac.Albums.FirstOrDefault(a => a.Name.Equals(albumName, StringComparison.OrdinalIgnoreCase));
            Photo = album.Photos.FirstOrDefault(p => p.DisplayName.Equals(photoName, StringComparison.OrdinalIgnoreCase));
            string name = Request.Form["name"] + Path.GetExtension(Photo.AbsolutePath);

            var newPhotoPath = new FileInfo(Path.Combine(album.AbsolutePath, name));
            int index = album.Photos.IndexOf(Photo);

            System.IO.File.Move(Photo.AbsolutePath, newPhotoPath.FullName);
            var newPhoto = new Photo(album, newPhotoPath);

            album.Photos.Insert(index, newPhoto);
            album.Photos.RemoveAt(index + 1);

            // Rename thumbnails
            string folder = Path.Combine(album.AbsolutePath, "thumbnail");
            var pattern = $"{Photo.DisplayName}-*x*{Path.GetExtension(Photo.AbsolutePath)}";

            foreach (var file in Directory.EnumerateFiles(folder, pattern))
            {
                string newThumbnail = Path.Combine(folder, Path.GetFileName(file).Replace(Photo.DisplayName, newPhoto.DisplayName));
                System.IO.File.Move(file, newThumbnail);
            }

            Photo.Album.Sort();

            return new RedirectResult($"~/photo/{WebUtility.UrlEncode(albumName).Replace('+', ' ')}/{newPhoto.DisplayName}/");

        }

        public IActionResult OnPostDelete(string albumName, string photoName)
        {
            var album = _ac.Albums.FirstOrDefault(a => a.Name.Equals(albumName, StringComparison.OrdinalIgnoreCase));
            Photo = album.Photos.FirstOrDefault(p => p.DisplayName.Equals(photoName, StringComparison.OrdinalIgnoreCase));
            album.Photos.Remove(Photo);

            if (System.IO.File.Exists(Photo.AbsolutePath))
            {
                System.IO.File.Delete(Photo.AbsolutePath);
                string folder = Path.Combine(album.AbsolutePath, "thumbnail");
                var pattern = $"{Photo.DisplayName}-*x*{Path.GetExtension(Photo.AbsolutePath)}";

                foreach (var file in Directory.EnumerateFiles(folder, pattern))
                {
                    System.IO.File.Delete(file);
                }
            }

            return new RedirectResult($"~/album/{WebUtility.UrlEncode(albumName).Replace('+', ' ')}/");
        }
    }
}

src/Pages/Album.cshtml
@page "{name}/{handler?}"
@model AlbumsModel
@{
    ViewData["Title"] = Model.Album.Name;
    ViewData["Description"] = $"The photo album \"{Model.Album.Name}\" containing {Model.Album.Photos.Count} photos including {string.Join(", ", Model.Album.Photos.Take(5))}";
    ViewData["Image"] = Request.Scheme + "://" + Request.Host + Model.Album.CoverPhoto?.GetThumbnailLink((int)ImageType.Full, out int h);
}

<div id="admin" if-authorized>
    <form method="post" enctype="multipart/form-data">
        <input type="file" id="files" aria-label="Upload photo" name="files" required multiple accept="image/*" />
        <input type="submit" asp-page-handler="upload" data-progress="Uploading..." id="btnfiles" value="Upload photos" />
    </form>

    <form method="post" class="delete">
        <input type="submit" asp-page-handler="delete" id="deletealbum" aria-label="Delete album..." title="Delete album..." value="X" />
    </form>
</div>

<div class="title" itemscope itemtype="http://schema.org/ListItem" itemprop="itemListElement">
    <paging model="@Model.Album" />
    <h2 itemscope itemtype="http://schema.org/Thing" itemprop="item">
        <span itemprop="name">@Model.Album.Name</span>
    </h2>
    <meta itemprop="position" content="2" />
</div>

<div class="pic photolist">
    @{
        foreach (Photo photo in Model.Album.Photos)
        {
            <a href="@photo.Link" data-text="@photo.DisplayName">
                <img photo="@photo" Type="Thumbnail" />
            </a>
        }
    }
</div>

@section scripts {
    <script if-authorized src="/js/admin.js" async></script>
}

@section head {
    <link if-authorized rel="stylesheet" href="/css/admin.scss" />
    @if (Model.Album.Next != null)
    {
        <link rel="next" href="@Model.Album.Next.Link" />
    }

    @if (Model.Album.Previous != null)
    {
        <link rel="prev" href="@Model.Album.Previous.Link" />
    }
}

src/Pages/Albums.cshtml
@page "{name}/{handler?}"
@model AlbumsModel

@{
    var ost = Model.Album.Name;
}

<div id="admin" if-authorized>
    <form method="post" enctype="multipart/form-data">
        <input type="file" id="files" aria-label="Upload photo" name="files" required multiple accept="image/*" />
        <input type="submit" asp-page-handler="upload" data-progress="Uploading..." id="btnfiles" value="Upload photos" />
    </form>

    <form method="post" class="delete">
        <input type="submit" asp-page-handler="delete" id="deletealbum" aria-label="Delete album..." title="Delete album..." value="🗙" />
    </form>
</div>

<div id="title">
    <h2>@Model.Album.Name</h2>
</div>

<section class="photolist">
    @{
        foreach (Photo photo in Model.Album.Photos)
        {
            <a href="@photo.Link">
                <figure class="album" itemscope itemtype="http://schema.org/CreativeWork">
                    <img photo="@photo" Type="Thumbnail" itemprop="image" />
                    <figcaption itemprop="name">@photo.DisplayName</figcaption>
                </figure>
            </a>
        }
    }
</section>

@section scripts {
    <script if-authorized src="~/js/admin.js" asp-append-version="true" async></script>
}

@section styles {
    <link if-authorized rel="stylesheet" href="~/css/admin.css" asp-append-version="true" />
}

src/Pages/Index.cshtml
@page
@inject AlbumCollection ac
@{
    ViewData["Title"] = "Albums";
    ViewData["Description"] = $"An online gallery where I share my photos with the world. Currently showing {ac.Albums.Count} albums ({string.Join(", ", ac.Albums.Select(a => a.Name))})";
    ViewData["Image"] = Request.Scheme + "://" + Request.Host + ac.Albums.FirstOrDefault()?.CoverPhoto?.GetThumbnailLink((int)ImageType.Full, out int h);
}

<form id="admin" if-authorized method="post" action="~/album/new/create/">
    <input type="text" name="name" id="name" aria-label="Album name" placeholder="Album name" required />
    <input type="submit" id="newalbum" data-progress="Creating..." value="New album">
</form>

@if (ac.Albums.Count == 0)
{
    <p>There are no albums yet. <a asp-page="Login">Sign in</a> to create new albums and upload photos.</p>
}

<h2>Albums</h2>

<div class="albumlist pic">
    @{
        foreach (Album album in ac.Albums)
        {
            var photo = album.CoverPhoto;
            if (photo != null)
            {
                <a href="/album/@album.UrlName/" data-text="@album.Name (@album.Photos.Count)">
                    <img photo="@photo" type="Thumbnail" />
                </a>
            }
            else
            {
                <a href="/album/@album.UrlName/" data-text="@album.Name">

                </a>
            }
        }
    }
</div>

@section head {
    <link if-authorized rel="stylesheet" href="/css/admin.scss" />
}

@section scripts {
    <script if-authorized src="/js/admin.js" async></script>
}

src/Pages/Login.cshtml
@page "{mode?}"
@model LoginModel
@{
    ViewData["Title"] = "Login";
    ViewData["Description"] = $"Sign in to the website";
    ViewData["Image"] = "";
    var referrer = Request.Headers["Referer"];
}

@section head {
    <link rel="stylesheet" href="/css/login.scss" />
}

<form method="post" id="login" aria-labelledby="legend">
    <fieldset>
        <legend id="legend">Sign in</legend>

        <input type="text" name="username" id="username" aria-label="Username" autofocus required placeholder="Username" />
        <input type="password" name="password" id="password" aria-label="Password" required placeholder="Password" />

        <input type="checkbox" name="remember" id="remember" />
        <label for="remember">Remember me</label>

        <input type="submit" value="Sign in" />
        <input type="hidden" name="referrer" value="@referrer" />
    </fieldset>
</form>

src/Pages/Photo.cshtml
@page "{albumName}/{photoName}/{handler?}"
@model PhotoModel
@{
    ViewData["Title"] = $"{Model.Photo.DisplayName} - {Model.Photo.Album.Name}";
    ViewData["Description"] = $"{Model.Photo.DisplayName} from the album {Model.Photo.Album.Name}";
    ViewData["Image"] = Request.Scheme + "://" + Request.Host + Model.Photo.GetThumbnailLink((int)ImageType.Full, out int h);
}

<div id="admin" if-authorized>
    <form method="post">
        <input type="text" name="name" aria-label="Name" required value="@Model.Photo.DisplayName" />
        <input type="submit" asp-page-handler="rename" data-progress="Renaming..." value="Rename photo" />
    </form>

    <form method="post" class="delete">
        <input type="submit" id="deletephoto" asp-page-handler="delete" aria-label="Delete photo..." title="Delete photo..." value="X" />
    </form>
</div>

<div class="title" itemscope itemtype="http://schema.org/ListItem" itemprop="itemListElement">
    <paging model="@Model.Photo" />
    <h2 itemscope itemtype="http://schema.org/Thing" itemprop="item">
        <span itemprop="name">@Model.Photo.DisplayName</span>
    </h2>
    <meta itemprop="position" content="3" />
</div>

<div class="photo">
    <div class="pic">
        <img photo="@Model.Photo" type="Full" />
    </div>

    <aside itemscope itemtype="http://schema.org/ListItem" itemprop="itemListElement">
        <meta itemprop="position" content="2" />
        <span>
            Posted in:
            <a href="@Model.Photo.Album.Link" itemscope itemtype="http://schema.org/Thing" itemprop="item">
                <span itemprop="name">@Model.Photo.Album.Name</span>
            </a>
        </span>
        <a href="@Model.Photo.DownloadLink" class="download">Download</a>
    </aside>
</div>

@section scripts{
    <script if-authorized src="/js/admin.js" async></script>
}

@section head {
    <link if-authorized rel="stylesheet" href="/css/admin.scss" />
    <link rel="index" href="@Model.Photo.Album.Link" />
    @if (Model.Photo.Next != null)
    {
        <link rel="next" href="@Model.Photo.Next.Link" />
    }

    @if (Model.Photo.Previous != null)
    {
        <link rel="prev" href="@Model.Photo.Previous.Link" />
    }
}

src/Pages/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" itemscope itemtype="http://schema.org/WebPage">
<head prefix="og: http://ogp.me/ns#">
    <meta charset="utf-8" />
    <title itemprop="name">@ViewData["Title"] - My Photo Gallery</title>
    <meta name="description" content="@ViewData["Description"]" />
    <meta name="keywords" content="@ViewData["Title"], photo, picture, gallery, images" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="/css/site.scss" inline />
    @RenderSection("head", required: false)
    <meta name="application-name" content="@ViewData["Title"]" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="@ViewData["Title"]" />
    <meta property="og:description" content="@ViewData["Description"]" />
    <meta property="og:url" content="@(Context.Request.Scheme + "://" + Context.Request.Host + Context.Request.Path)" />
    <meta property="og:image" content="@ViewData["Image"]" />
    <link rel="shortcut icon" href="~/img/icon16x16.png" />
    <link rel="apple-touch-icon" href="~/img/icon180x180.png" />
</head>
<body>
    <div itemscope itemtype="http://schema.org/BreadcrumbList" itemprop="breadcrumb">
        <header>
            <div class="container" itemscope itemprop="itemListElement" itemtype="http://schema.org/ListItem">
                <h1>
                    <a href="~/" title="Back to the home page" itemscope itemtype="http://schema.org/Thing" itemprop="item">
                        <span itemprop="name">My Photo Gallery</span>
                    </a>
                </h1>
                <meta itemprop="position" content="1" />
            </div>
        </header>

        <main class="container">
            @RenderBody()
            @{await Html.RenderPartialAsync("_SocialButtons.cshtml", ViewData["Title"]);}
        </main>
    </div>

    <footer>
        <p class="container">
            Fork me on <a href="https://github.com/madskristensen/PhotoGallery" rel="noreferrer noopener" title="See the source code">GitHub</a>
            @{await Html.RenderPartialAsync("_LoginButton.cshtml");}
        </p>
    </footer>

    <script src="/js/site.js" inline></script>
    @RenderSection("scripts", required: false)

    <meta itemprop="description" content="@ViewData["Description"]" />
    <meta itemprop="image" content="@ViewData["Image"]" />
</body>
</html>

src/Pages/_LoginButton.cshtml
@{
    string path = Context.Request.Path;

    if (User.Identity.IsAuthenticated)
    {
        <a href="~/login/?returnUrl=@path&logout=1" title="Sign out as administrator">Sign out</a>
    }
    else
    {
        <a href="~/login/" title="Sign in as administrator">Sign in</a>
    }
}